### ISSUE TITLE
Vagrantfile fails to start mesos instance on mac

### ISSUE THREAD

**Issue by spuder** [duedil-ltd/portainer#8]
If you attmept to run `vagrant up` on MacOSX, you get the following error

```
git clone https://github.com/duedil-ltd/portainer.git

foo@Foo-MacBook-Pro:~/Downloads/portainer$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'debian-73-x64-virtualbox-nocm' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Adding box 'debian-73-x64-virtualbox-nocm' (v0) for provider: virtualbox
    default: Downloading: debian-73-x64-virtualbox-nocm
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /Users/foo/Downloads/portainer/debian-73-x64-virtualbox-nocm
```

**Comment by orls** [comment]
I [made a note about this in the readme](https://github.com/duedil-ltd/portainer/commit/45264cd5362e346032f0c8a20fe11ced326f8842#diff-04c6e90faac2675aa89e2176d2eec7d8) while doing some recent changes. It's a nonstandard / non-core box, so you need to add it on your machine before you first run `vagrant up`

`vagrant box add debian-73-x64-virtualbox-nocm http://puppet-vagrant-boxes.puppetlabs.com/debian-73-x64-virtualbox-nocm.box`
